font:
  normal:
    family: Iosevka
  size: 13

window:
  padding:
    x: 10
    y: 10

colors:
  primary:
    background: '0x121212'
    foreground: '0xdedede'
  cursor:
    text:   '0xffffff'
    cursor: '0xffffff'
  normal:
    black:   '0x929292'
    red:     '0xe27373'
    green:   '0x94b979'
    yellow:  '0xffba7b'
    blue:    '0x97bedc'
    magenta: '0xe1c0fa'
    cyan:    '0x00988e'
    white:   '0xdedede'
  bright:
    black:   '0xbdbdbd'
    red:     '0xffa1a1'
    green:   '0xbddeab'
    yellow:  '0xffdca0'
    blue:    '0xb1d8f6'
    magenta: '0xfbdaff'
    cyan:    '0x1ab2a8'
    white:   '0xffffff'

