font:
  normal:
    family: Noto Sans Mono
  size: 12

window:
  padding:
    x: 10
    y: 10

env:
  WINIT_X11_SCALE_FACTOR: "1"

# Colors (Gruvbox Material Dark Medium)
colors:
  primary:
    background: '0x282828'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

colors:
  primary:
    background: '0x121212'
    foreground: '0xdedede'
  cursor:
    text:   '0xffffff'
    cursor: '0xffffff'
  normal:
    black:   '0x929292'
    red:     '0xe27373'
    green:   '0x94b979'
    yellow:  '0xffba7b'
    blue:    '0x97bedc'
    magenta: '0xe1c0fa'
    cyan:    '0x00988e'
    white:   '0xdedede'
  bright:
    black:   '0xbdbdbd'
    red:     '0xffa1a1'
    green:   '0xbddeab'
    yellow:  '0xffdca0'
    blue:    '0xb1d8f6'
    magenta: '0xfbdaff'
    cyan:    '0x1ab2a8'
    white:   '0xffffff'
