#!/bin/sh

pid=$(pgrep wf-recorder)
if (exit $?) then
	for x in $pid; do
		kill -INT $x
	done

	for x in $pid; do
		tail --pid=$x -f /dev/null
	done
else
	nohup wf-recorder -f ~/videos/records/rec-$(date +"%m.%d.%y-%H:%M:%S").mp4 -o eDP-1 --audio=alsa_output.pci-0000_00_1f.3.analog-stereo.monitor -c h264_vaapi -d /dev/dri/renderD128 &
	sleep 0.3; rm -rf nohup.out
fi

pkill -RTMIN+8 waybar
