#!/bin/sh

pid=$(pgrep wf-recorder)
if (exit $?) then
	for x in pid; do
		kill - # todo
	done
fi

nohup wf-recorder -f ~/videos/records/rec-$(date +"%m.%d.%y-%H:%M:%S").mp4 -o eDP-1 --audio=alsa_output.pci-0000_00_1f.3.analog-stereo.monitor -c h264_vaapi -d /dev/dri/renderD128 &
rm -rf nohup.out
