#!/bin/sh

export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"
export XDG_CURRENT_DESKTOP=sway
export WAYLAND_DISPLAY=wayland-1

# export into activation environment to make it visible to other services
dinitctl setenv DBUS_SESSION_BUS_ADDRESS || :
dinitctl setenv XDG_CURRENT_DESKTOP || :
dinitctl setenv WAYLAND_DISPLAY || :

exec dbus-daemon --session --address="$DBUS_SESSION_BUS_ADDRESS" "$@"
